provider: "null"
major-version: 0
providerDefaultBranch: main
makeTemplate: bridged
publishRegistry: false
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
env:
    NULL_TOKEN: ${{ secrets.NULL_TOKEN }}
pulumiConvert: 1
plugins:
    - name: std
      version: "1.6.2"
    - name: terraform
      version: "1.0.16"
      kind: converter
