provider: "null"
major-version: 0
providerDefaultBranch: main
makeTemplate: bridged
publishRegistry: false
esc:
    enabled: true
    environment: imports/github-secrets # No repo-specific secrets.
env:
    NULL_TOKEN: ${{ secrets.NULL_TOKEN }}
pulumiConvert: 1
