// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package null

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi-null/sdk/go/null/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// ## Example Usage
func GetDataSource(ctx *pulumi.Context, args *GetDataSourceArgs, opts ...pulumi.InvokeOption) (*GetDataSourceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDataSourceResult
	err := ctx.Invoke("null:index/getDataSource:getDataSource", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDataSource.
type GetDataSourceArgs struct {
	// If set, its literal value will be stored and returned. If not, its value defaults to `"default"`. This argument exists primarily for testing and has little practical use.
	HasComputedDefault *string `pulumi:"hasComputedDefault"`
	// A map of arbitrary strings that is copied into the `outputs` attribute, and accessible directly for interpolation.
	Inputs map[string]string `pulumi:"inputs"`
}

// A collection of values returned by getDataSource.
type GetDataSourceResult struct {
	// If set, its literal value will be stored and returned. If not, its value defaults to `"default"`. This argument exists primarily for testing and has little practical use.
	HasComputedDefault string `pulumi:"hasComputedDefault"`
	// This attribute is only present for some legacy compatibility issues and should not be used. It will be removed in a future version.
	//
	// Deprecated: This attribute is only present for some legacy compatibility issues and should not be used. It will be removed in a future version.
	Id string `pulumi:"id"`
	// A map of arbitrary strings that is copied into the `outputs` attribute, and accessible directly for interpolation.
	Inputs map[string]string `pulumi:"inputs"`
	// After the data source is "read", a copy of the `inputs` map.
	Outputs map[string]string `pulumi:"outputs"`
	Random  string            `pulumi:"random"`
}

func GetDataSourceOutput(ctx *pulumi.Context, args GetDataSourceOutputArgs, opts ...pulumi.InvokeOption) GetDataSourceResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetDataSourceResultOutput, error) {
			args := v.(GetDataSourceArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("null:index/getDataSource:getDataSource", args, GetDataSourceResultOutput{}, options).(GetDataSourceResultOutput), nil
		}).(GetDataSourceResultOutput)
}

// A collection of arguments for invoking getDataSource.
type GetDataSourceOutputArgs struct {
	// If set, its literal value will be stored and returned. If not, its value defaults to `"default"`. This argument exists primarily for testing and has little practical use.
	HasComputedDefault pulumi.StringPtrInput `pulumi:"hasComputedDefault"`
	// A map of arbitrary strings that is copied into the `outputs` attribute, and accessible directly for interpolation.
	Inputs pulumi.StringMapInput `pulumi:"inputs"`
}

func (GetDataSourceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDataSourceArgs)(nil)).Elem()
}

// A collection of values returned by getDataSource.
type GetDataSourceResultOutput struct{ *pulumi.OutputState }

func (GetDataSourceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDataSourceResult)(nil)).Elem()
}

func (o GetDataSourceResultOutput) ToGetDataSourceResultOutput() GetDataSourceResultOutput {
	return o
}

func (o GetDataSourceResultOutput) ToGetDataSourceResultOutputWithContext(ctx context.Context) GetDataSourceResultOutput {
	return o
}

// If set, its literal value will be stored and returned. If not, its value defaults to `"default"`. This argument exists primarily for testing and has little practical use.
func (o GetDataSourceResultOutput) HasComputedDefault() pulumi.StringOutput {
	return o.ApplyT(func(v GetDataSourceResult) string { return v.HasComputedDefault }).(pulumi.StringOutput)
}

// This attribute is only present for some legacy compatibility issues and should not be used. It will be removed in a future version.
//
// Deprecated: This attribute is only present for some legacy compatibility issues and should not be used. It will be removed in a future version.
func (o GetDataSourceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDataSourceResult) string { return v.Id }).(pulumi.StringOutput)
}

// A map of arbitrary strings that is copied into the `outputs` attribute, and accessible directly for interpolation.
func (o GetDataSourceResultOutput) Inputs() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetDataSourceResult) map[string]string { return v.Inputs }).(pulumi.StringMapOutput)
}

// After the data source is "read", a copy of the `inputs` map.
func (o GetDataSourceResultOutput) Outputs() pulumi.StringMapOutput {
	return o.ApplyT(func(v GetDataSourceResult) map[string]string { return v.Outputs }).(pulumi.StringMapOutput)
}

func (o GetDataSourceResultOutput) Random() pulumi.StringOutput {
	return o.ApplyT(func(v GetDataSourceResult) string { return v.Random }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDataSourceResultOutput{})
}
