// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.null_;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import com.pulumi.null_.Utilities;
import com.pulumi.null_.inputs.GetDataSourceArgs;
import com.pulumi.null_.inputs.GetDataSourcePlainArgs;
import com.pulumi.null_.outputs.GetDataSourceResult;
import java.util.concurrent.CompletableFuture;

public final class NullFunctions {
    /**
     * The `null.getDataSource` data source implements the standard data source lifecycle but does not
     * interact with any external APIs.
     * 
     * Historically, the `null.getDataSource` was typically used to construct intermediate values to re-use elsewhere in configuration. The
     * same can now be achieved using locals or the terraformData resource type in Terraform 1.4 and later.
     * 
     */
    public static Output<GetDataSourceResult> getDataSource() {
        return getDataSource(GetDataSourceArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * The `null.getDataSource` data source implements the standard data source lifecycle but does not
     * interact with any external APIs.
     * 
     * Historically, the `null.getDataSource` was typically used to construct intermediate values to re-use elsewhere in configuration. The
     * same can now be achieved using locals or the terraformData resource type in Terraform 1.4 and later.
     * 
     */
    public static CompletableFuture<GetDataSourceResult> getDataSourcePlain() {
        return getDataSourcePlain(GetDataSourcePlainArgs.Empty, InvokeOptions.Empty);
    }
    /**
     * The `null.getDataSource` data source implements the standard data source lifecycle but does not
     * interact with any external APIs.
     * 
     * Historically, the `null.getDataSource` was typically used to construct intermediate values to re-use elsewhere in configuration. The
     * same can now be achieved using locals or the terraformData resource type in Terraform 1.4 and later.
     * 
     */
    public static Output<GetDataSourceResult> getDataSource(GetDataSourceArgs args) {
        return getDataSource(args, InvokeOptions.Empty);
    }
    /**
     * The `null.getDataSource` data source implements the standard data source lifecycle but does not
     * interact with any external APIs.
     * 
     * Historically, the `null.getDataSource` was typically used to construct intermediate values to re-use elsewhere in configuration. The
     * same can now be achieved using locals or the terraformData resource type in Terraform 1.4 and later.
     * 
     */
    public static CompletableFuture<GetDataSourceResult> getDataSourcePlain(GetDataSourcePlainArgs args) {
        return getDataSourcePlain(args, InvokeOptions.Empty);
    }
    /**
     * The `null.getDataSource` data source implements the standard data source lifecycle but does not
     * interact with any external APIs.
     * 
     * Historically, the `null.getDataSource` was typically used to construct intermediate values to re-use elsewhere in configuration. The
     * same can now be achieved using locals or the terraformData resource type in Terraform 1.4 and later.
     * 
     */
    public static Output<GetDataSourceResult> getDataSource(GetDataSourceArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("null:index/getDataSource:getDataSource", TypeShape.of(GetDataSourceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * The `null.getDataSource` data source implements the standard data source lifecycle but does not
     * interact with any external APIs.
     * 
     * Historically, the `null.getDataSource` was typically used to construct intermediate values to re-use elsewhere in configuration. The
     * same can now be achieved using locals or the terraformData resource type in Terraform 1.4 and later.
     * 
     */
    public static Output<GetDataSourceResult> getDataSource(GetDataSourceArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("null:index/getDataSource:getDataSource", TypeShape.of(GetDataSourceResult.class), args, Utilities.withVersion(options));
    }
    /**
     * The `null.getDataSource` data source implements the standard data source lifecycle but does not
     * interact with any external APIs.
     * 
     * Historically, the `null.getDataSource` was typically used to construct intermediate values to re-use elsewhere in configuration. The
     * same can now be achieved using locals or the terraformData resource type in Terraform 1.4 and later.
     * 
     */
    public static CompletableFuture<GetDataSourceResult> getDataSourcePlain(GetDataSourcePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("null:index/getDataSource:getDataSource", TypeShape.of(GetDataSourceResult.class), args, Utilities.withVersion(options));
    }
}
