// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The `null.getDataSource` data source implements the standard data source lifecycle but does not
 * interact with any external APIs.
 *
 * Historically, the `null.getDataSource` was typically used to construct intermediate values to re-use elsewhere in configuration. The
 * same can now be achieved using locals or the terraformData resource type in Terraform 1.4 and later.
 */
export function getDataSource(args?: GetDataSourceArgs, opts?: pulumi.InvokeOptions): Promise<GetDataSourceResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("null:index/getDataSource:getDataSource", {
        "hasComputedDefault": args.hasComputedDefault,
        "inputs": args.inputs,
    }, opts);
}

/**
 * A collection of arguments for invoking getDataSource.
 */
export interface GetDataSourceArgs {
    /**
     * If set, its literal value will be stored and returned. If not, its value defaults to `"default"`. This argument exists primarily for testing and has little practical use.
     */
    hasComputedDefault?: string;
    /**
     * A map of arbitrary strings that is copied into the `outputs` attribute, and accessible directly for interpolation.
     */
    inputs?: {[key: string]: string};
}

/**
 * A collection of values returned by getDataSource.
 */
export interface GetDataSourceResult {
    /**
     * If set, its literal value will be stored and returned. If not, its value defaults to `"default"`. This argument exists primarily for testing and has little practical use.
     */
    readonly hasComputedDefault: string;
    /**
     * This attribute is only present for some legacy compatibility issues and should not be used. It will be removed in a future version.
     *
     * @deprecated This attribute is only present for some legacy compatibility issues and should not be used. It will be removed in a future version.
     */
    readonly id: string;
    /**
     * A map of arbitrary strings that is copied into the `outputs` attribute, and accessible directly for interpolation.
     */
    readonly inputs?: {[key: string]: string};
    /**
     * After the data source is "read", a copy of the `inputs` map.
     */
    readonly outputs: {[key: string]: string};
    /**
     * A random value. This is primarily for testing and has little practical use; prefer the hashicorp/random provider for more practical random number use-cases.
     */
    readonly random: string;
}
/**
 * The `null.getDataSource` data source implements the standard data source lifecycle but does not
 * interact with any external APIs.
 *
 * Historically, the `null.getDataSource` was typically used to construct intermediate values to re-use elsewhere in configuration. The
 * same can now be achieved using locals or the terraformData resource type in Terraform 1.4 and later.
 */
export function getDataSourceOutput(args?: GetDataSourceOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDataSourceResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("null:index/getDataSource:getDataSource", {
        "hasComputedDefault": args.hasComputedDefault,
        "inputs": args.inputs,
    }, opts);
}

/**
 * A collection of arguments for invoking getDataSource.
 */
export interface GetDataSourceOutputArgs {
    /**
     * If set, its literal value will be stored and returned. If not, its value defaults to `"default"`. This argument exists primarily for testing and has little practical use.
     */
    hasComputedDefault?: pulumi.Input<string>;
    /**
     * A map of arbitrary strings that is copied into the `outputs` attribute, and accessible directly for interpolation.
     */
    inputs?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
}
